"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import clsx from "clsx";
import { listProposals } from "@/lib/api";
import type { GatewayStatus, ProposalResponse } from "@/lib/types";
import { PageHeader } from "@/components/page-header";
import { GatewayBadge } from "@/components/badges";

const PAGE_SIZE = 25;

export default function ProposalsPage() {
  const [proposals, setProposals] = useState<ProposalResponse[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState<string>("ALL");
  const [offset, setOffset] = useState(0);

  useEffect(() => {
    let cancelled = false;
    setProposals(null);
    listProposals({ limit: 100 })
      .then((data) => {
        if (cancelled) return;
        setProposals(data);
      })
      .catch((e) => !cancelled && setError(String(e.message ?? e)));
    return () => {
      cancelled = true;
    };
  }, []);

  const filtered = useMemo(() => {
    if (!proposals) return null;
    return proposals.filter((p) => {
      if (statusFilter !== "ALL" && p.gateway_status !== statusFilter) {
        return false;
      }
      if (search) {
        const q = search.toLowerCase();
        const hay = [p.proposal_id, p.target_table]
          .filter(Boolean)
          .join(" ")
          .toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    });
  }, [proposals, statusFilter, search]);

  if (error) {
    return (
      <div className="space-y-6">
        <PageHeader title="Proposals" />
        <div className="card border-danger-border bg-danger-bg p-4 text-sm text-danger">
          {error}
        </div>
      </div>
    );
  }

  const loading = proposals === null;
  const total = proposals?.length ?? 0;
  const slice = filtered?.slice(offset, offset + PAGE_SIZE) ?? [];
  const hasMore = filtered ? offset + PAGE_SIZE < filtered.length : false;
  const hasPrev = offset > 0;

  return (
    <div className="space-y-6 anim-fade">
      <PageHeader
        title="Proposals"
        description="Schema-evolution proposals generated by the agent. Each entry holds the drift assessment, gateway classification, and the generated transformation code."
        actions={
          <Link href="/ingest" className="btn-primary">
            New ingest
          </Link>
        }
      />

      <div className="flex items-center gap-3 flex-wrap">
        <input
          type="text"
          className="input w-80"
          placeholder="Search proposal ID or target table…"
          value={search}
          onChange={(e) => {
            setSearch(e.target.value);
            setOffset(0);
          }}
        />
        <select
          className="input w-44"
          value={statusFilter}
          onChange={(e) => {
            setStatusFilter(e.target.value);
            setOffset(0);
          }}
        >
          <option value="ALL">All classifications</option>
          <option value="AUTO_LINK">Auto Link</option>
          <option value="SCHEMA_EVOLUTION">Schema Evolution</option>
          <option value="CONFLICT">Conflict</option>
        </select>
        <div className="ml-auto text-2xs text-fg-muted font-mono">
          {filtered?.length ?? "—"} of {total}
        </div>
      </div>

      <div className="panel">
        {loading ? (
          <div className="panel-body space-y-2">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="h-10 rounded bg-bg-subtle anim-fade" />
            ))}
          </div>
        ) : filtered && filtered.length > 0 ? (
          <table className="table-base">
            <thead>
              <tr>
                <th>Proposal ID</th>
                <th>Target table</th>
                <th>Gateway</th>
                <th>Drift</th>
                <th>Confidence</th>
                <th>PII</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {slice.map((p) => {
                const confidencePct = Math.round(p.confidence_score * 100);
                const confidenceColor =
                  p.confidence_score > 0.9
                    ? "text-success"
                    : p.confidence_score > 0.75
                    ? "text-warning"
                    : "text-danger";
                return (
                  <tr key={p.proposal_id}>
                    <td className="font-mono text-2xs text-fg-muted">
                      {p.proposal_id.slice(0, 8)}…
                    </td>
                    <td className="font-mono text-xs">
                      {p.target_table ?? (
                        <span className="text-fg-subtle">—</span>
                      )}
                    </td>
                    <td>
                      <GatewayBadge status={p.gateway_status} />
                    </td>
                    <td className="font-mono tabular-nums text-sm">
                      {p.drift_detected.length}
                    </td>
                    <td>
                      <span
                        className={clsx(
                          "font-mono tabular-nums text-sm",
                          confidenceColor,
                        )}
                      >
                        {confidencePct}%
                      </span>
                    </td>
                    <td className="text-2xs text-fg-muted font-mono">
                      {p.pii_columns_found.length === 0
                        ? "—"
                        : p.pii_columns_found.join(", ")}
                    </td>
                    <td className="text-right">
                      <Link
                        href={`/proposals/${p.proposal_id}`}
                        className="text-2xs text-fg-muted hover:text-fg"
                      >
                        View →
                      </Link>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        ) : (
          <div className="panel-body text-sm text-fg-muted">
            No proposals match these filters.{" "}
            <Link href="/ingest" className="text-fg underline">
              Ingest a file
            </Link>{" "}
            to generate one.
          </div>
        )}
      </div>

      {filtered && filtered.length > PAGE_SIZE ? (
        <div className="flex items-center justify-between text-2xs text-fg-muted">
          <div>
            Showing {offset + 1}–
            {Math.min(offset + PAGE_SIZE, filtered.length)} of {filtered.length}
          </div>
          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}
              disabled={!hasPrev}
              className="btn-secondary h-7"
            >
              ← Prev
            </button>
            <button
              onClick={() => setOffset(offset + PAGE_SIZE)}
              disabled={!hasMore}
              className="btn-secondary h-7"
            >
              Next →
            </button>
          </div>
        </div>
      ) : null}
    </div>
  );
}
